name: cimtools-master
channels:
  - conda-forge
  - rdkit
dependencies:
  - python>=3.7.0
  - pandoc
  - rdkit
  - pip
  - ipython
  - wheel
  - lxml
  - sphinx_rtd_theme
  - nbsphinx
  - pip:
    - CGRtools
    - .
